language: c

os:
  - linux
  - osx

dist: bionic
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libtool autoconf git nasm pkg-config cmake; fi
  - chmod +x install.sh
  - ./install.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

