language: c

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then alias nasm=/usr/local/bin/nasm; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libtool autoconf git nasm pkg-config cmake; fi
  - chmod +x install.sh
  - ./install.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

after_success:
  - demo/caesiumd -v
