[package]
name = "libcaesium"
version = "0.12.0"
authors = ["Matteo Paonessa <matteo.paonessa@gmail.com>"]
edition = "2021"
categories = ["multimedia::images"]
keywords = [
    "compression",
    "library",
    "jpeg",
    "png",
    "gif",
    "webp"
]
description = "A lossy/lossless image compression library."
readme = "README.md"
exclude = [
    "tests/*",
]
homepage = "https://github.com/Lymphatus/libcaesium"
repository = "https://github.com/Lymphatus/libcaesium"
license = "Apache-2.0"

[dependencies]
mozjpeg-sys = { version = "1.0", optional = true }
oxipng = { version = "8.0", optional = true }
libc = "0.2"
gifsicle = { version = "1.92.5", optional = true }
webp = { version = "0.2.2", optional = true }
infer = "0.13.0"
image = { version = "0.24.6", default-features = false, features = ["jpeg", "png", "webp", "gif"] }
img-parts = "0.3"
bytes = "1.1"
lodepng = { version = "3.7", optional = true }
imagequant = {version = "4.1", optional = true}

[features]
default = ["jpg", "png", "webp", "gif"]
jpg = ["dep:mozjpeg-sys"]
png = ["dep:oxipng", "dep:lodepng", "dep:imagequant"]
webp = ["dep:webp"]
gif = ["dep:gifsicle"]

[dev-dependencies]
dssim = "3.2.0"
kamadak-exif = "0.5.4"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "caesium"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
test = true
doctest = false
bench = false
doc = false
