[package]
name = "libcaesium"
version = "0.9.3"
authors = ["Matteo Paonessa <matteo.paonessa@gmail.com>"]
edition = "2021"
categories = ["multimedia::images"]
keywords = [
    "compression",
    "library",
    "jpeg",
    "png",
    "gif",
    "webp"
]
description = "A lossy/lossless image compression library."
readme = "README.md"
exclude = [
    "tests/*",
]
homepage = "https://github.com/Lymphatus/libcaesium"
repository = "https://github.com/Lymphatus/libcaesium"
license = "Apache-2.0"

[dependencies]
mozjpeg-sys = "1.0.2"
oxipng = "6.0.1"
libc = "0.2"
gifsicle = "1.92.5"
webp = "0.2"
infer = "0.9"
image = { version = "0.24.3", default-features = false, features = ["jpeg", "png", "webp", "gif"] }
img-parts = "0.3"
bytes = "1.1"
lodepng = "3.7"
imagequant = {git = "https://github.com/Lymphatus/libimagequant", rev = "67f1686"}

[dev-dependencies]
dssim = "3.2.0"
kamadak-exif = "0.5.4"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "caesium"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]
test = true
doctest = false
bench = false
doc = false
